# **QUESTION 1 -- Expresions, variables, and type**

## 1a

In [ ]:
seconds_in_minute = 60
minutes_in_hour = 60

print(f'there are {seconds_in_minute} seconds in a minute')
print(f'there are {minutes_in_hour} minutes in an hour')

there are 60 seconds in a minute
there are 60 minutes in an hour

**TODO: 1.a** Write an expression that uses the two given variables to compute the number of seconds in 3 hours, 40 minutes, and 9 seconds. (The answer is 13209).

In [ ]:
minutes_in_xyz = (3*minutes_in_hour)+40
seconds_in_xyz = (seconds_in_minute * minutes_in_xyz)+9

print(f'there are {seconds_in_xyz} seconds in 3 hours, 40 minutes, and 9 seconds.')

there are 13209 seconds in 3 hours, 40 minutes, and 9 seconds.

## 1b

**TODO: 1.b** In the code cell below, create a variable called total_seconds. Set it equal to the expression you composed in 1.a.

In [ ]:
total_seconds=seconds_in_xyz

## 1c

**TODO: 1.c**. In the code cell below, you'll note that the variable mins_per_hour has been changed. Explain why your code gives an error.

In [ ]:
seconds_in_minute = 60
minutes_in_hour = "60"

minutes_in_xyz = (3*minutes_in_hour)+40
seconds_in_xyz = (seconds_in_minute * minutes_in_xyz)+9

print(f'there are {seconds_in_xyz} seconds in 3 hours, 40 minutes, and 9 seconds.')

TypeError: can only concatenate str (not "int") to str

**YOUR EXPLANATION (1c)**

Answer:
A string can not be mathamatically calcualated as if it were an int value. It would have to first be converted to an int or floating point number.

## 1d

**TODO 1.d**: Execute the two print statements below, as described in the assignment. Explain why you observed the difference.

In [ ]:
print("Imagination is more important than knowledge,for knowledge is limited, whereas imagination encircles the world - Albert Einstein")

Imagination is more important than knowledge,for knowledge is limited, whereas imagination encircles the world - Albert Einstein

In [ ]:
print("\"Imagination is more important than knowledge,\nfor knowledge is limited, whereas imagination\nencircles the world.\"\n\t- Albert Einstein")

"Imagination is more important than knowledge,
for knowledge is limited, whereas imagination
encircles the world."
	- Albert Einstein

**YOUR EXPLANATION (1d):**

Answer: In the first code block it is simply printing a string with no line spacing or returns, however the second code block includes escape codes for line breaks and quotes.

## 1e

**TODO: 1.e** Execute the cell below, and explain your observations.

In [ ]:
len(625.417)

TypeError: object of type 'float' has no len()

In [ ]:
len("625.417")

7

Describe why `len()` behaves differently in the two cases above. If you observed errors, explain them in simple language.

**YOUR EXPLANATION (1e):**

Answer: In the second code block, the code executes correctly and states the float value has a length of 7, however in the first code block it is unable to calculate the length of the input. This is because len() is meant for float values only.

## 1f

**TODO 1.f** Execute the two code blocks below. Explain why they evaluate differently. What is your hypothesis?

In [ ]:
9 > 10

False

In [ ]:
"9" > "10"

True

**YOUR EXPLANATION (1f):**

Answer: In the first code block, we are asking the computer if 9 is greater than 10, to which it correctly retuns false. In the second code block, we are telling the computer that the string "9" is greater than the string "10".

## 1g

**TODO 1.g** In the code block below, write two expressions that test your hypothesis. Then, explain why you think your tests are important ones.

In [10]:
11<10

"11"<"10"

True

**YOUR EXPLANATION (1g)**

Answer: It turns out I was incorrect in my previous hypothesis. After doing some research, it turns out that when comparing strings using ">" or "<" it is actually using the strings unicode value to compare them.

# **QUESTION 2 -- A bit more with type**

## 2a & b

In [13]:
# Run this block on several choices of *test_num*
# one example is provided for you

test_num = int(9)

(test_num % 2) == 0 & (test_num > 5)

False

**YOUR EXPLANATION (2b)**

Answer: The two numbers I used for testing were 9 and 10. I chose thesse numbers as 10 should return true and 9 should return false. This was correct and 9 did return false and 10 did return true.

## 2c

**YOUR EXPLANATION (2c)**

Answer: The modulo operator returns the remainder of a division problem.

# **QUESTION 3 -- A fun calculation**

In [42]:
# Your code for 3a here:
test_year=2025
test_year%4==0

False

In [32]:
# Your code for 3b here:
test_year%100==0

True

In [33]:
# Your code for 3c here:
test_year%100!=0

False

In [34]:
# Your code for 3d here:
test_year%400==0

True

In [46]:
# Your code for 3e here:
passes_century_exception=(test_year%100==0)and(test_year%400==0)
print(passes_century_exception)

False

In [44]:
# Your code for 3f here:
passes_4yr_nc_test=(test_year%4==0)and(test_year%100!=00)
print(passes_4yr_nc_test)

False

In [47]:
# Your code for 3g here:
passes_all_tests=(passes_4yr_nc_test==True) and (passes_century_exception==True)
print(passes_all_tests)

#Answer: It does not correctly evaluate if a year is a leap year because a leap year could be divisible by 100.

False

In [ ]:
# Your code for 3h here: No a number could not pass both of these tests as they contradict each other.

**YOUR EXPLANATION for 3i here**

Answer: It would be OR not AND because both can not be true however either of them being true means it is a leap year.

In [48]:
# Your code for 3j here:
is_leap_year=(passes_4yr_nc_test==True) or (passes_century_exception==True)
print(is_leap_year)

False

**YOUR EXPLANATION for 3k here**

Answer: Yes, this should check correctly if a yera is a leap year.

# **QUESTION 4 -- Playing with some data**

In [67]:
# Make sure you run this!
import pandas as pd
import seaborn as sns

df = sns.load_dataset('tips') # creates a pandas dataframe

In [66]:
# Your code for 4a here:

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

**YOUR EXPLANATION FOR 4A HERE:**

Answer: I noticed that the describe has much more detail (more decimal places shown) than head. It appears that head rounds the data down to the nearest 0.01 and also shows other data such as day and sex. The shape meathod did not work for me as I got an error.

**YOUR EXPLANATION FOR 4B HERE:**

Answer: I would research if there was a correlation between age and tipping culture. I would also be interested to see if sex played a role in tipping culture.

**YOUR EXPLANATION FOR 4C HERE:**

Answer: To see if sex played a role in tipping, I would first seperate the data into 2 datasets by sex and then calculate the average tip for each of these two datasets. Then by comparing the results I could see if there is any significant difference between male and female tippers.

In [78]:
# Your code for 4d here:
df['tip_percent'] = df['tip'] / df['total_bill'] *100
df.head()

,total_bill,tip,sex,smoker,day,time,size,tip_percent,Sun,Sat,Thur,Fri
0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673,Friday,Friday,Friday,Friday
1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159,Friday,Friday,Friday,Friday
2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734,Friday,Friday,Friday,Friday
3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041,Friday,Friday,Friday,Friday
4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765,Friday,Friday,Friday,Friday

In [82]:
# Your code for 4e here:

df[df['day']="Fri"]

,total_bill,tip,sex,smoker,day,time,size,tip_percent,Sun,Sat,Thur,Fri
2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734,Friday,Friday,Friday,Friday
3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041,Friday,Friday,Friday,Friday
4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765,Friday,Friday,Friday,Friday
5,25.29,4.71,Male,No,Sun,Dinner,4,18.623962,Friday,Friday,Friday,Friday
7,26.88,3.12,Male,No,Sun,Dinner,4,11.607143,Friday,Friday,Friday,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...
232,11.61,3.39,Male,No,Sat,Dinner,2,29.198966,Friday,Friday,Friday,Friday
234,15.53,3.00,Male,Yes,Sat,Dinner,2,19.317450,Friday,Friday,Friday,Friday
238,35.83,4.67,Female,No,Sat,Dinner,3,13.033771,Friday,Friday,Friday,Friday
239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697,Friday,Friday,Friday,Friday
243,18.78,3.00,Female,No,Thur,Dinner,2,15.974441,Friday,Friday,Friday,Friday